### PR TITLE
Made the ad-on support ROLE_DOCUMENT, so it works with the new Notepad and other such things.

### LINKED ISSUE #7: Totally nonfunctional in Windows Notepad
STR:

1. Install Notepad from the Microsoft store.
2. Open it
3. Try to use indent nav commands.

This seems to have broken with the notepad rewrite.

### PR DESCRIPTION
**Pull request by TheQuinbox**
Closes #7

### CODE REVIEW

**Comment by mltony** [comment]
Did you test it in other apps?  It shouldn't trigger in browse mode or in Microsoft Word/WordPad - all of them have document as role.

**Comment by TheQuinbox** [comment]
It always triggered in WordPad, as its ROLE_EDITABLETEXT. I don't have generic word to test it with, though.

**Comment by mltony** [comment]
What about browse mode in browsers? I just checked that focused element 
role appears to always be document. We don't want to trigger IndentNav 
in browsers.

**Comment by TheQuinbox** [comment]
Ooh, excellent point. What else could we check for? Some property on the control?

**Comment by mltony** [comment]
TBH not sure, it would probably require some tinkering. IIRC findOverlay 
function is called pretty early so browse mode stuff maybe haven't been 
initialized by then. I would suggest maybe check window class - if it is 
unique for new notepad. Another solution - more fundamental - would be 
to patch EditableText class and inject all keystrokes there instead of 
trying to use NVDAObject API, but this would be a bigger effort.

**Comment by TheQuinbox** [comment]
Okay, we now check for the window class being RichEditD2DPT. All seems to work as expected.

**Pull request merged**
